  # --- CORE Services ---
services:
  # --- CADDY (Reverse proxy) ---
  caddy:
    build: ./config/caddy/
    container_name: caddy
    restart: unless-stopped
    profiles: [essential, all]
    ports:
      - "80:80"
      - "443:443"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CADDY_EMAIL=${CADDY_EMAIL}
    volumes:
      - ${CONFIG_ROOT}/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${APP_CONFIG_PATH}/caddy/data:/data
      - ${APP_CONFIG_PATH}/caddy/config:/config
    networks:
      - media-network

  # --- HOMEPAGE ---
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    profiles: [essential, all]
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3001:3000"
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=*
      - HOMEPAGE_VAR_TAILSCALE_IP=${TAILSCALE_IP}
      - HOMEPAGE_VAR_PLEX_TOKEN=${PLEX_API_TOKEN}
      - HOMEPAGE_VAR_PIHOLE_TOKEN=${PIHOLE_PASSWORD}
      - HOMEPAGE_VAR_QBIT_PASSWORD=${QBIT_PASSWORD}
      - HOMEPAGE_VAR_OVERSEERR_TOKEN=${OVERSEERR_API_KEY}
      - HOMEPAGE_VAR_PROWLARR_TOKEN=${PROWLARR_API_KEY}
      - HOMEPAGE_VAR_RADARR_TOKEN=${RADARR_API_KEY}
      - HOMEPAGE_VAR_SONARR_TOKEN=${SONARR_API_KEY}
      - HOMEPAGE_VAR_SPEEDTEST_TOKEN=${SPEEDTEST_API_KEY}
      - HOMEPAGE_VAR_JELLYFIN_TOKEN=${JELLYFIN_API_KEY}
    volumes:
      - ${CONFIG_ROOT}/homepage:/app/config
      - ${CONFIG_ROOT}/homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_ROOT}:${DATA_ROOT}:ro
    networks:
      - media-network

  # --- SPEEDTEST ---
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    profiles: [essential, moni, all]
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DB_CONNECTION=sqlite
      - APP_KEY=${SPEEDTEST_KEY}
      - SPEEDTEST_SCHEDULE="0 * * * *" #"*/15 * * * *"
      - PRUNE_RESULTS_OLDER_THAN=30 # 30 days
    volumes:
      - ${APP_CONFIG_PATH}/speedtest-tracker:/config
      - ${DATA_DB_ROOT}/speedtest.sqlite:/config/database.sqlite
    ports:
      - "8443:80"
    networks:
      - media-network
  # Temp credentials
  # Email: admin@example.com
  # Pass: password

  # --- PiHole -AdBlock ---
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    profiles: [essential, all]
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      FTLCONF_webserver_port: 8081
      WEBPASSWORD: ${PIHOLE_PASSWORD}
    volumes:
      - ${APP_CONFIG_PATH}/pihole:/etc/pihole
      - ${APP_CONFIG_PATH}/dnsmasq.d:/etc/dnsmasq.d
    network_mode: host

networks:
  media-network:
    external: true