# --- MONITORING ---
services:
  # --- PUSHGATEWAY (Metrics receiver) ---
  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - "9091:9091"
    networks:
      - media-network


  # --- PROMETHEUS (TSDB database) ---
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    user: "root"
    ports:
      - "9090:9090"
    volumes:
      - ${CONFIG_ROOT}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ${APP_CONFIG_PATH}/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - media-network


  # --- GRAFANA (Dashboard visual) ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: "root"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ${APP_CONFIG_PATH}/grafana/data:/var/lib/grafana
      - ${CONFIG_ROOT}/grafana/provisioning:/etc/grafana/provisioning:ro
      - ${CONFIG_ROOT}/grafana/dashboards_json:/etc/grafana/dashboards_json:ro
    networks:
      - media-network

networks:
  media-network:
    external: true