services:
  # --- HOMEPAGE (Dashboard) ---
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "3001:3000" # Entrarás por el puerto 3001
    volumes:
      - ${CONFIG_ROOT}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock # Para ver el estado de los contenedores
    networks:
      - media-network

  # --- PLEX (Media Player) ---
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${CONFIG_ROOT}/plex:/config
      # Plex lee directamente de la carpeta de medios final
      - ${DATA_ROOT}/media:/media

  # --- QBITTORRENT (Downloader) ---
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=${QBIT_WEBUI_PORT}
    volumes:
      - ${CONFIG_ROOT}/qbittorrent:/config
      # Importante: Mapeamos /data para descargar en /data/torrents
      - ${DATA_ROOT}:/data
    ports:
      - "${QBIT_WEBUI_PORT}:${QBIT_WEBUI_PORT}"
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - media-network

  # --- PROWLARR (Indexer Manager) ---
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG_ROOT}/prowlarr:/config
    ports:
      - "9696:9696"
    networks:
      - media-network

  # --- RADARR (Movies) ---
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG_ROOT}/radarr:/config
      # Radarr necesita acceso a /data completo (descargas + destino) para mover archivos
      - ${DATA_ROOT}:/data
    ports:
      - "7878:7878"
    networks:
      - media-network

  # --- SONARR (TV Series) ---
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG_ROOT}/sonarr:/config
      - ${DATA_ROOT}:/data
    ports:
      - "8989:8989"
    networks:
      - media-network
  
  # --- OVERSEERR (Request Management) ---
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/overseerr:/config
    ports:
      - "5055:5055"
    networks:
      - media-network
      
  # --- BOTS ---
  test-bot:
    build: ./bots/pocoyo
    container_name: test-bot
    restart: unless-stopped
    environment: 
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
  
  pol-academy-offers-bot:
    build: https://github.com/PlatanosVerdes/PolFerrerAcademyOffers.git#add_bot_logic #main
    container_name: pol-academy-offers-bot
    restart: unless-stopped
    environment: 
      BOT_TOKEN: ${BOT_POL_ACADEMY_OFFERS_TOKEN}
      


networks:
  media-network:
    driver: bridge