services:
  # --- HOMEPAGE (Dashboard) ---
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 127.0.0.1
    ports:
      - "3001:3000"
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=192.168.1.180,192.168.1.180:3001,100.125.71.20,100.125.71.20:3001,localhost,home.pi
    volumes:
      - ${CONFIG_ROOT}/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - media-network

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 8.8.8.8
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp" # Panel de control (puedes cambiarlo a 8081:80 si el 80 está ocupado)
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${PIHOLE_PASSWORD}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      FTLCONF_LOCAL_IPV4: ${STATIC_IP}
    volumes:
      - ${CONFIG_ROOT}/pihole:/etc/pihole
      - ${CONFIG_ROOT}/dnsmasq.d:/etc/dnsmasq.d
    networks:
      - media-network

  # --- PLEX (Media Player) ---
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${CONFIG_ROOT}/plex:/config
      - ${DATA_ROOT}:/data

  # --- QBITTORRENT (Downloader) ---
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - WEBUI_PORT=${QBIT_WEBUI_PORT}
    dns:
      - 8.8.8.8
      - 127.0.0.1
    volumes:
      - ${CONFIG_ROOT}/qbittorrent:/config
      - ${DATA_ROOT}:/data
    ports:
      - "${QBIT_WEBUI_PORT}:${QBIT_WEBUI_PORT}"
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - media-network

  # --- PROWLARR (Indexer Manager) ---
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 127.0.0.1
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG_ROOT}/prowlarr:/config
    ports:
      - "9696:9696"
    networks:
      - media-network

  # --- RADARR (Movies) ---
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 127.0.0.1
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG_ROOT}/radarr:/config
      - ${DATA_ROOT}:/data
    ports:
      - "7878:7878"
    networks:
      - media-network

  # --- SONARR (TV Series) ---
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG_ROOT}/sonarr:/config
      - ${DATA_ROOT}:/data
    ports:
      - "8989:8989"
    networks:
      - media-network
  
  # --- OVERSEERR (Request Management) ---
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 127.0.0.1
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/overseerr:/config
    ports:
      - "5055:5055"
    networks:
      - media-network
  
  # BOTS 
  pol-academy-offers-bot:
    build: https://github.com/PlatanosVerdes/PolFerrerAcademyOffers.git#main
    container_name: pol-academy-offers-bot
    restart: unless-stopped
    network_mode: host
    environment: 
      BOT_TOKEN: ${BOT_POL_ACADEMY_OFFERS_TOKEN}
      


networks:
  media-network:
    driver: bridge