{
 "title": "One Pace Arc Status",
 "tags": [
  "one-pace",
  "media"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Total arcs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(onepace_arc_episodes_on_disk{job=\"one-pace-downloader\"})"
    }
   ]
  },
  {
   "title": "Total episodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "onepace_episodes_on_disk{job=\"one-pace-downloader\"}"
    }
   ]
  },
  {
   "title": "Arcs in Spanish",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(onepace_arc_episodes_on_disk{job=\"one-pace-downloader\",lang=\"es\"})"
    }
   ]
  },
  {
   "title": "Arcs English-only",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(onepace_arc_episodes_on_disk{job=\"one-pace-downloader\",lang=\"en\"})"
    }
   ]
  },
  {
   "title": "Arc Status",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "onepace_arc_episodes_on_disk{job=\"one-pace-downloader\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}