{
 "title": "Pi-hole ver6 Stats",
 "description": "A dashboard for the pihole6_exporter.",
 "tags": [
  "pihole6",
  "pihole"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Host",
    "query": {
     "query": "label_values(pihole_client_count,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Totals Over Range", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clients (Top 10)",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum_over_time(pihole_query_client_1m{instance=\"$instance\"}[$__range]))",
     "legendFormat": "{{query_client}}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_client_count{instance=\"$instance\",category=\"active\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "pihole_client_count{instance=\"$instance\",category=\"total\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "topk(20,sum_over_time(pihole_query_type_1m{instance=\"$instance\"}[$__range]))",
     "legendFormat": "{{query_type}}"
    }
   ]
  },
  {
   "title": "Ads Blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(pihole_query_status_1m{instance=\"$instance\",query_status=~\"(GRAVITY.*|SPECIAL_DOMAIN)\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocked %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(pihole_query_status_1m{instance=\"$instance\",query_status=~\"(GRAVITY.*|SPECIAL_DOMAIN)\"}[$__range])) / sum(sum_over_time(pihole_query_status_1m{instance=\"$instance\"}[$__range])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upstream DNS",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum_over_time(pihole_query_upstream_1m{instance=\"$instance\"}[$__range])",
     "legendFormat": "{{query_upstream}}"
    }
   ]
  },
  {
   "title": "Queries by Status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum_over_time(pihole_query_status_1m{instance=\"$instance\"}[$__range])",
     "legendFormat": "{{query_status}}"
    }
   ]
  },
  {
   "title": "Query Replies",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(pihole_query_reply_1m{instance=\"$instance\"}[$__range])",
     "legendFormat": "{{query_reply}}"
    }
   ]
  },
  {
   "title": "Clients (Full List)",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10,sum_over_time(pihole_query_client_1m{instance=\"$instance\"}[$__range]))",
     "legendFormat": "{{query_client}}"
    }
   ]
  },
  {
   "title": "Queries Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries by Status (10m)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 13, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum_over_time(pihole_query_status_1m{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{query_status}}"
      }
     ]
    },
    {
     "title": "Queries by Type (10m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum_over_time(pihole_query_type_1m{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{query_type}}"
      }
     ]
    },
    {
     "title": "Queries by Upstream Destination (10m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum_over_time(pihole_query_upstream_1m{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{query_upstream}}"
      }
     ]
    },
    {
     "title": "Queries by Client (10m)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 13, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum_over_time(pihole_query_client_1m{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{query_client}}"
      }
     ]
    },
    {
     "title": "Queries by Reply (10m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum_over_time(pihole_query_reply_1m{instance=\"$instance\"}[$__interval])",
       "legendFormat": "{{query_reply}}"
      }
     ]
    }
   ]
  }
 ]
}